---
title: "STA2202: Final Project"
output:
  pdf_document: default
  header-includes:
    - \usepackage{setspace}\doublespacing
  fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Statistical Methods
```{r explore}
library("astsa")
tsplot(gtemp2)
abline(h=mean(gtemp2))
acf(gtemp2)
pacf(gtemp2)
```
```{r transform}
transformed_data <- diff(gtemp2)
tsplot(transformed_data, main="Time Series Plot of diff(gtemp2)")
abline(h=mean(transformed_data))
par(mfcol=c(2,1))
acf(transformed_data)
pacf(transformed_data)
```

# Results
```{r estimate1}
model1 <- sarima(gtemp2, p=2, d=1, q=3, no.constant = FALSE)
```
```{r estimate2}
library(tidyverse)
model2 <- sarima(gtemp2, p=1, d=1, q=3, no.constant = FALSE)
AIC <- round(c(model1$AIC, model2$AIC),4)
AICc <- round(c(model1$AICc, model2$AICc),4)
BIC <- round(c(model1$BIC, model2$BIC),4)
Model <- c("ARMA(2,1,3)", "ARMA(1,1,3)")
print(AIC)
pred <- sarima.for(gtemp2, 10, 1, 1, 3, no.constant = FALSE)
```

```{r prediction}
se <- sarima.for(gtemp2,10,p=1,d=1,q=3,no.constant=FALSE, plot = FALSE)$se
predict_value <- sarima.for(gtemp2,10,p=1,d=1,q=3,no.constant=FALSE, plot = FALSE)$pred
year <- c(2010:2019)
CI90_upper <- predict_value + qnorm(0.975)*se
CI90_lower <- predict_value - qnorm(0.975)*se
print(cbind(year, predict_value, CI90_lower, CI90_upper))
```


```{r spectral}
library(MASS)
spect <- mvspec(gtemp2, log="no")
# spect$details has frequency, period, spectrum, and we want to find the
# frequencies of the ones with top 3 spectrum
# [,3] means this sorting based on spectrum's value
ordered_details <- spect$details[order(spect$details[,3], decreasing = TRUE),]
upper1 <- 2*ordered_details[1,3]/qchisq(0.025,2)
lower1 <- 2*ordered_details[1,3]/qchisq(0.975,2)
upper2 <- 2*ordered_details[2,3]/qchisq(0.025,2)
lower2 <- 2*ordered_details[2,3]/qchisq(0.975,2)
upper3 <- 2*ordered_details[3,3]/qchisq(0.025,2)
lower3 <- 2*ordered_details[3,3]/qchisq(0.975,2)
lower_bound <- c(lower1, lower2, lower3)
upper_bound <- c(upper1, upper2, upper3)
frequency <- cbind(ordered_details[1,], ordered_details[2,], ordered_details[3,])[1,]
period <- cbind(ordered_details[1,], ordered_details[2,], ordered_details[3,])[2,]
spectrum <- cbind(ordered_details[1,], ordered_details[2,], ordered_details[3,])[3,]
print(cbind(frequency, 1/frequency,spectrum, lower_bound, upper_bound))
```

